// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkawsgyvfrzlpsjowvdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYXdzZ3l2ZnJ6bHBzam93dmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNDM2NjUsImV4cCI6MjA3OTYxOTY2NX0.VW655DRDyiWWH-DhOAgJO-RjtAljYNXaNViCmtCOlt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});